### ISSUE TITLE
pagination's current page dose not equal url's parameter "p"

### ISSUE THREAD

**Issue by terranboy** [algolia/examples#16]
current page = p+1

**Comment by vvo** [comment]
Hi @terranboy indeed that's because the internal Algolia engine API design is bubbling up to your url bar: pagination starts at 0 in Algolia engine.

Thus in the url you have the true search state mapping Algolia API while when displayed we show the right "user API" which means we display p + 1.

That should not be so much of a big deal for your users but could be for developers, we got that.

You could still fix it in your application by putting p + 1 also in the url and sending p - 1 to Algolia.

**Comment by vvo** [comment]
(For reference, in react-instantsearch, we are gonna fix this for good)
