### ISSUE TITLE
Travis builds are errorring because of submodules checkout

### ISSUE THREAD

**Issue by pixelastic** [algolia/examples#24]
The current Travis config tries to pull the two submodules from this repo but is failing because it does not have the correct access rights.

We can fix this either by using `https` urls for submodules so no access right is needed, but it will prevent developers from pushing from those submodules when developping locally.

We can also tell Travis to not pull submodules by adding this to the config and completly ignoring the issue:

```
git:
    submodules: false
```

But it means that Travis won't be able to run the linting process on the submodules, and that we hope that each submodule will have correctly applied the linting. I'd rather not remove the lint check in here (even if it is currently not working, see #23).

The best way would be to create a GitHub user with a specific key and share this key with Travis so it can correctly pull everything.

Or... we can hack our way around with this:

```
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
```

([Source](http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci)).

What do you think? I'm ok with the hacky solution, but if someone has the courage to create the needed GitHub permissions that'd be even better.

**Comment by proudlygeek** [comment]
Hey Folks,

Unfortunately creating a specific user doesn't seem possible on https://travis-ci.org but only on Travis Pro:

https://docs.travis-ci.com/user/private-dependencies/#User-Key

Using deploy keys would be definitely awkward (one per submodule), I'd go for the hack.

**Comment by dongyuanxin** [comment]
@proudlygeek 
I generate sshkey with `travis` shell locally. 
![image](https://user-images.githubusercontent.com/26399528/66391455-c0145100-e9ff-11e9-8d97-2d2482da629d.png)

And I'm sure that the sshkey has been added into github setting and travis repository setting. 
![image](https://user-images.githubusercontent.com/26399528/66391534-f782fd80-e9ff-11e9-960a-3d88d224762f.png)

However, travis built fail because of the short of permission to read repository.
![image](https://user-images.githubusercontent.com/26399528/66391708-70825500-ea00-11e9-9542-a0702864efb4.png)

[Detailed Build Report](https://travis-ci.com/dongyuanxin/blog/builds/130875641). Is there any step I did not follow the documentation? 

Waiting for your reply, thank you

**Comment by hermanbanken** [comment]
For people Googling this, this checkbox in Travis Pro can help:
![Screenshot 2020-10-22 at 16 17 10](https://user-images.githubusercontent.com/791189/96884794-33a9c480-1482-11eb-969a-adf489acd65e.png)
It is at https://travis-ci.com/github/your-org/your-repo/settings
